APPLICATION_NAME: Karr demo
API_PORT: 1993
API_BASE: http://localhost:1993
LOG_TIMESTAMP: true
ADMIN_EMAIL: foo@bar.com
FEDERATION: true
FEDERATION_TARGETS:
    - name: Karr Live
      url: https://karr.finxol.io
DB_CONFIG:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    db_name: postgres
