name: Deploy Auth Server to Deno Deploy

on:
    push:
        branches:
            - main
            - ci/auto-deploy-auth
        paths:
            - "apps/auth-server/**"
            - "packages/auth/**"
            - ".github/workflows/deploy-auth-server.yaml"
            - "pnpm-workspace.yaml"

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Needed for auth with Deno Deploy
            contents: read # Needed to clone the repository
            pull-requests: write # Needed to comment on PRs

        steps:
            - uses: actions/checkout@v3
              name: Checkout repository

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - uses: actions/setup-node@v3
              name: Setup Node.js
              with:
                  node-version: 22
                  cache: pnpm

            - name: Install turbo
              run: pnpm add turbo --global

            - name: Install Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x

            - name: Prune repository
              run: turbo prune "@karr/auth-server"

            - name: Install dependencies
              run: |
                  cd out
                  pnpm install

            - name: Build dependencies
              run: |
                  cd out
                  pnpm run --filter '!@karr/auth-server' build

            - name: Type check
              run: |
                  cd out
                  pnpm run check:types

            - name: Build auth server
              run: |
                  cd out/apps/auth-server
                  deno run -A script/bundle.ts

            - name: Install deployctl
              run: deno install -gArf jsr:@deno/deployctl

            - name: Deploy to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: karr-auth
                  entrypoint: server.mjs
                  root: out/apps/auth-server/out
